### ISSUE TITLE
Update Data Identification instruction text for DOIs

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/metadata-entry-form#102]
In the Data Identification section, change the instruction text from: 

'What is the dataset identifier, eg DOI or other unique ID?'

to something like:

Enter the data set DOI (omitting https://doi.org/) eg. 10.21966/1.566666

**Comment by n-a-t-e** [comment]
The text has been changed to
_What is the DOI for this dataset? Eg, https://doi.org/10.0000/0000_

I think it will be simpler for people to leave it in, we can remove the  `https://doi.org/` automatically if needed

**Comment by Br-Johnson** [comment]
It looks like the https://doi.org/ is not being removed automatically and therefore is duplicated in the auto generated citation:
![image](https://user-images.githubusercontent.com/26495640/127404414-65afa9f2-089b-4115-a98e-5570380d04c1.png)

However, the "Citation Identifier" looks fine:
![image](https://user-images.githubusercontent.com/26495640/127404489-d4c193cd-1899-46a8-bfd6-195c6a831ba6.png)

**Comment by n-a-t-e** [comment]
The example text was updated, otherwise I'd say this is a CKAN issue
