### ISSUE TITLE
Change output namespace from ca-coos to ca-cioos

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-entry-form#112]
This typo shows in the YAML and XML namespace (ca.coos) and then ultimately in all the CKAN record URLs harvested from those.

**Comment by n-a-t-e** [comment]
Should be fixed by 241102a2e23594c321500985e63bf0ebc0e2d090, reopen if you still see it happening anywhere

**Comment by jeffcullis** [comment]
Awesome, it is working well, thanks Nate!
