### ISSUE TITLE
non alphanumeric characters in keywords

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/metadata-entry-form#118]
Currently non alphanumeric characters such as ',' are allowed in keywords.

But ckan validator does not accept them....

so maybe the form should not allow them as well

**Comment by n-a-t-e** [comment]
We are doing a sprint on keywords now and it sounds like in the near future, we may be limiting keywords to a specific keyword list. So that might make this issue go away

**Comment by n-a-t-e** [comment]
See https://github.com/cioos-siooc/cioos-siooc-standards/pull/16

The current plan is to add a link to a Github issue template, so a user can suggest new keywords easily, as long as they have a Github account.

**Comment by ogsletcax** [comment]
Thx!! good to know! I'm closing this issue then!
