### ISSUE TITLE
Admin/Reviewer pages

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#12]
We could create an 'Admin' user level. Admins  could login and 'approve' datasets, which will flag them in the database for ingestion into CKAN.

**Comment by fostermh** [comment]
Depending on what features are implemented you may want to consider 3 user levels: [creator, reviewer, admin]. Admin's would have the power to change user levels and perhaps perform maintenance actions like removing abandoned records and such. Reviewers and Admin's could approve records for ingestion.

**Comment by n-a-t-e** [comment]
Yes, that's what we decided at our last stand up meeting as well. I like the term reviewer over 'admin' too. I don't think there will be an immediate need for a higher (admin) in this version but maybe at another point.
