### ISSUE TITLE
AWS Translate text length limit

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#128]
Apparently the max size of text to be translated at once by AWS for their quick translate API is 5kb. @Mbrownshoes got an error when trying to translate a long abstract from a Hakai dataset -  `Input text size exceeds limit. Max length of request text allowed is 5000 bytes while in this request the text size is 5990 bytes`

Some options to fix this -
 - cap the abstract to 600 words (or another size) and let the user know of this limit
 - send multiple requests to translate the whole thing

@fostermh - does CKAN have any issues with really long abstracts? The one that broke it is almost 1000 words

Do we want to discourage long absracts for other reasons as well? if not we can just do mulitple requests

**Comment by fostermh** [comment]
ckan does not have a limit per field. the Solr indexing does limit words per field but it is very large like 32K words or something like that. Limiting to some set number of words makes sense to me. Abstracts should be short. extra info can be placed in the attached documents if needed.
