### ISSUE TITLE
Make French keywords required to submit a form

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/metadata-entry-form#150]
The international year of the salmon catalogue (http://iys.hakai.org) fails to be harvested by CIOOS Pacific catalogue because some records don't have French keywords according to @fostermh. I think then it makes sense that the metadata intake form requires at least one French keyword before the record can be submitted to avoid issues with harvesting.

**Comment by n-a-t-e** [comment]
From ISO19115_Profile_CIOOS_Version2_2020-07, I cant tell
![Screen Shot 2021-10-19 at 5 19 56 PM](https://user-images.githubusercontent.com/26209011/138007701-7c0ae539-76bf-4d23-a45d-65a0d9de2ba1.png)

**Comment by n-a-t-e** [comment]
I'm not sure that having a french keyword is a CIOOS requirement. We are currently populating the Gov't of Canada thesaurus keyword 'Ocean' for all datasets (not shown in the form), so we can just add `Océan` if needed, to all datasets

https://canada.multites.net/cst/default.asp?op=DISPTERM&searchString=Oceans&lang=ENG

**Comment by Br-Johnson** [comment]
Just curious @fostermh whether harvesting the IYS Catalogue to CIOOS Pacific is possible now?

**Comment by fostermh** [comment]
it appears that yes it does now work.
