### ISSUE TITLE
MD_Metadata should be MI_Metadata in XML

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-entry-form#170]
The XML generated from the form uses MD_Metadata but we should be using MI_Metadata.

**Comment by n-a-t-e** [comment]
As far as I can tell, `MI_Metadata` is from
ISO 19115-2, while we are using ISO 19115-3. The XML generated by the form validates to the ISO 19115-3 using this XSD file https://standards.iso.org/iso/19115/-3/mds/2.0/mds.xsd.

The XML generated by ONC also follows this, eg https://data.oceannetworks.ca/ISO19115XMLService?datasetType=fixedScalar&siteDeviceId=1193241 (behind firewall)

See https://github.com/cioos-siooc/cioos-iso-validate

Or please link to some information supporting the change if I am missing something

**Comment by jeffcullis** [comment]
You're right that we're using ISO19115-3 in terms of how to generate the XML, but -3 defines how to make XML that conforms with both -1 and -2. The -1 document defines MD_Metadata, and then since we're adding instrument / aquisition metadata from -2, we need the MI_Metadata that extends MD_Metadata and adds the aquisition elements to it.

**Comment by fostermh** [comment]
@jeffcullis interestingly I recently read the same thing while working on a related project.

**Comment by n-a-t-e** [comment]
We already have sections for  `acquisitionInformation` and `instrument`, see:

`/mdb:MD_Metadata/mdb:acquisitionInformation/mac:MI_AcquisitionInformation/mac:platform/mac:MI_Platform/mac:instrument`

And note that this is in a valid XML document with a root element of `mdb:MD_Metadata`.

So I'm not seeing the issue here that needs to be resolved, but please share more info to support the use of `MI_Metadata` in case there's something I'm not seeing here

**Comment by fostermh** [comment]
sorry guys I think I added to the confusion. So here are some interesting things. ISO19115-2 does recommend using the MI_Metadata tag for imagery and gridded data. That does sound like us in most cases. However, we have implemented the XML using ISO19115-3. They are different.

# NOAA write up on ISO19115-2
https://www.ncei.noaa.gov/sites/default/files/2020-04/ISO%2019115-2%20Workbook_Part%20II%20Extentions%20for%20imagery%20and%20Gridded%20Data.pdf

# ISO Defenition of ISO19115-3
https://www.iso.org/standard/32579.html#:~:text=ISO%2FTS%2019115%2D3%3A2016%20describes%20the%20procedure%20used,from%20the%20conceptual%20UML%20model.

In ISO19115-2 we would use 'gmd' and 'gmi' namespaces. in ISO19115-3 we are using 'mdb' namespace.
So.. I'm not sure were we go from here. given that we have so much time invested in our current infrastructure it would be a same to junk it and redo the XML in -2
