### ISSUE TITLE
Discrepancy between citation preview in form vs. result in CKAN

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/metadata-entry-form#172]
From what I can infer the citation preview in the metadata intake form shows the year the data was published, whereas in CKAN the citation year is based on the revised date (if it exists).

**Comment by Br-Johnson** [comment]
Also publiser shows up in CKAN APA style citation as follows:

Creator (PublicationYear): Title. (resourceTypeGeneral). Publisher. Identifier

But the citation preview in the metadata form doesn't include publisher. Lastly, identifying a publisher in the metadata intake form is not documented with tool tips indicating the special prominence of this role.

**Comment by n-a-t-e** [comment]
So is publisher supposed to be in the citation? If so I can add it as a starred role, and it will appear in the preview

**Comment by Br-Johnson** [comment]
I see the star has been added to the publisher role but it doesn't appear in the recommended citation still. With the new 'Appear in Citation' check box, can you make it so that the Publisher always appears in the Citation after the Dataset Title (same as CKAN)

For eg. in CKAN:

Pakhomov, E., Weitkamp, L., Neville, C., Somov, A., King, J., Farley, E., Hunt, B., Freshwater, C., Murphy, J., Stap, T. van der, Johnson, B., Kivva, K., Esenkulova, S., Urawa, S., Waters, C., Vazhova, A., Radchenko, V., Riddel, B., Beamish, R., … Saunders, M. (2022). Integrated Data Collection from the International Year of the Salmon High Seas Expeditions [Data set]. North Pacific Anadromous Fish Commission. https://doi.org/10.21966/81jn-6p63

vs. in metadata entry tool:

Pakhomov, E., Weitkamp, L., Neville, C., Somov, A., King, J., Farley, E., Hunt, B., Freshwater, C., Murphy, J., van der Stap, T., Johnson, B., Kivva, K., Esenkulova, S., Urawa, S., Waters, C., Vazhova, A., Radchenko, V., Riddel, B., Beamish, R., … Saunders, M. (2022). Integrated Data Collection from the International Year of the Salmon High Seas Expeditions. https://doi.org/10.21966/81jn-6p63
