### ISSUE TITLE
Abondance et distribution de tortues marines, oiseaux et mammifères eov problem

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/metadata-entry-form#193]
Datasets with the eov "Abondance et distribution de tortues marines, oiseaux et mammifères" fail to be harvested.

The harvester error is triggered because of the "," character.

In the xml, the **eov code** is used for the english version but the **eov translation** is used for the french version:
```
<mri:keyword>						
<gco:CharacterString>Abondance et distribution de tortues marines, oiseaux et mammifères</gco:CharacterString>						
</mri:keyword>	
<mri:keyword xsi:type="lan:PT_FreeText_PropertyType">						
<lan:PT_FreeText>							
<lan:textGroup>								
<lan:LocalisedCharacterString locale="#en">marineTurtlesBirdsMammalsAbundanceAndDistribution</lan:LocalisedCharacterString>								
</lan:textGroup>							
</lan:PT_FreeText>						
</mri:keyword>
```

First i was thinking that using the eov code for the french version as well could do the job (change this line? https://github.com/cioos-siooc/metadata-entry-form/blob/7af4f9c3493337a967082124cd0dab483ff5b5d0/firebase_to_xml/firebase_to_xml/record_json_to_yaml.py#L115)

But i guess it won't be  translated in the tag section of the dataset in the catalogue. So i don't know.

What do you think could the best way to fix this?

@n-a-t-e @fostermh

**Comment by fostermh** [comment]
alternatively, I could change the validator to allow commas (,). I noticed that in some of your test files you also had a semi-colon (;). should semi-colons also be allowed? any other characters?
