### ISSUE TITLE
Metadata entry form fields for converting to French - Data and Resources section bilingual Names and Descriptions

### ISSUE THREAD

**Issue by jacobthompson101** [cioos-siooc/metadata-entry-form#204]
This issue is in regard to the Data and Resources section that displays on CKAN but is populated from the metadata entries. Specifically the Names are in English only, but the Descriptions have both an English and French field. Currently if you click French, all of the content on the page translates except for this text in the Data and Resources section.

See the original issue raised on the CKAN repo, as a linked issue.
https://github.com/cioos-siooc/ckan/issues/166

**Describe the bug**
Data and Resources section in CKAN dataset page not translated into French when switching (remains in English).

**Comment by n-a-t-e** [comment]
I agree that we should make "resource name" a bilingual entry field. Although I don't know if that will solve your problem as it won't be required in both french and english, so I assume if someone leaves out french it will just use the english text.

![Screen Shot 2022-06-23 at 1 55 39 PM](https://user-images.githubusercontent.com/26209011/175398544-ce649802-5a3f-4406-864e-43628c0f2b21.png)
