### ISSUE TITLE
Add missing form fields

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#22]
Here is a list of some forms fields that exist in the YAML that we haven't yet included in the form. 

  - keywords (non-eov)
  - identifier
  - vertical extent
  - project (can be a list)
  - acknowledgement
  - platform authority

The profile has many more <http://cioosatlantic.ca/profile/>

**Comment by fostermh** [comment]
Also, depending on the chosen path forward:

- license.title
- license.url

currently have license.code

- spatial.polygon
- temporal_duration (could be calculated)
- time_coverage_resolution
- contact.individual.contry (may not be needed, not sure)

**Comment by n-a-t-e** [comment]
See #16 for spatial.polygon

**Comment by ogsletcax** [comment]
@n-a-t-e i can't find any description of the fields:
- project (can be a list)
- acknowledgement
- platform authority
 
in https://cioosatlantic.ca/profile/ 
nor https://docs.google.com/spreadsheets/d/1j2Us0B3F4b3STj_lSE0B_VqS47PxmesifG2cugj0Mak/edit#gid=956981416

Is there any other reference document?

**Comment by n-a-t-e** [comment]
Hm, good point, wonder if we should get rid of those fields left over from Pygeometa/ACDD if they're not in the profile. Do we need `project` and `acknowledgement` @jeffcullis @sjbruce @fostermh ?

I do see platform authority in the google sheet, see:

MI_AcquisitionInformation
platform>MI_Platform
>identifier>MD_Identifier
>>authority

**Comment by fostermh** [comment]
I'm not sure how project or acknowledgment would be used in our case. I wondered what they were for also. :-)

**Comment by sjbruce** [comment]
According to this they both have mappings for ISO 19115-2 or at least they did - there is a disclaimer at the top that states:

> "These mappings are no longer normative—they represent the original relation of ACDD attributes to similar concepts in other specifications, but have not been updated for the latest changes."

https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_Mappings

Might be something to ask metadata about - they are fields that are covered/supported by ERDDAP dataset definitions as well.

https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html#acknowledgement

https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html#project

**Comment by n-a-t-e** [comment]
See #28 for identifier

**Comment by n-a-t-e** [comment]
As for `temporal_duration` and `time_coverage_resolution`, these also fall into the category of not part of the CIOOS profile. They are also not required by the ISO schema. I propose we get rid of them everywhere, they are also annoying to deal with as they use the ISO 8601 duration format (an example duration is `P3Y6M4DT12H30M5S`, whatever that means)

**Comment by fostermh** [comment]
sounds fine to me.

**Comment by fostermh** [comment]
also looks like project maps to keywords in two of the three instances fro the docks Scott linked. Not sure that is very useful as users could just add to keywords directly. Achnowledgement's maps to credit which is not required by anyone. might be nice if someone wants to indicate who paid for the research or something but not required for sure.
