### ISSUE TITLE
cannot change manually email when ORCID is used

### ISSUE THREAD

**Issue by pauline-chauvet** [cioos-siooc/metadata-entry-form#220]
If a person has not updated its ORCID but we have the information, it could be nice to still have the ORCID but be able to edit manually the info (I understand that it can be problematic when people change of organizations but if there is nothing yet in their ORCID...):
ex with ORCID, the email section is empty and I cannot edit it 
![image](https://user-images.githubusercontent.com/70213496/208692328-f101f3d3-9269-4088-8681-958888d73144.png)

same ex without ORCID
![image](https://user-images.githubusercontent.com/70213496/208692532-6a755461-ad72-4cd9-85c8-fc951ce3b977.png)

**Comment by n-a-t-e** [comment]
Sure, we could make name and email editable on the ORCID side of things. What do you think about ROR? Maybe just the Organization name could be not editable

**Comment by n-a-t-e** [comment]
Fixed by #222, or feel free to reopen the issue if you need to be able to edit more fields
