### ISSUE TITLE
Restrictive minimal date 1899

### ISSUE THREAD

**Issue by julieDionne** [cioos-siooc/metadata-entry-form#221]
Minimum date in the metadata entry tool causes problems for historical data. For the moment the minimum date is 1899, could we move it back in time, or not put a minimum date?

![image](https://user-images.githubusercontent.com/79526012/210637705-aa623824-ca7e-4929-87b8-2291a5a2ee18.png)

**Comment by n-a-t-e** [comment]
fixed by https://github.com/cioos-siooc/metadata-entry-form/commit/4966665c874a291dc7fc1e014a3338dadd8832be
