### ISSUE TITLE
DOI creation from metadata form

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#225]
DOI creation can happen from within the metadata form. This would allow any user to create a *draft* DOI only. To publish the draft, users with DataCite credentials would login into the DataCite page and publish manually.

The metadata form could access the DataCite API via a firebase function, using credentials stored something like [this](https://github.com/cioos-siooc/metadata-entry-form/blob/37c7c6a99a6f0419d36393c2c444a59798a678a5/.github/workflows/firebase-deploy.yaml#L28)  way

If an existing DOI entered in the metadata tool Data Identification section matches a stored DataCite credential (by matching repo ID), then that record could be updateable as well by the form.

_DOI dropdown_
 - Open DOI link
      - Available for all datasets with published DOIs
 - Go to DOI draft in data cite ?
      - This option would required login
 - Submit/Update DOI draft (would show submit or update depending if already been submitted)
 - Delete Draft

**Comment by sorochak** [comment]
https://github.com/cioos-siooc/metadata-entry-form/pull/229
