### ISSUE TITLE
Better explanation of Platform ID question

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#226]
Its unclear what users should put in that field- is it a complete URL or just a code.

Could list code types with examples:
- IMO: eg 7510846
- WMO: eg 45141

What other vocabularies are commonly used?

**Comment by timvdstap** [comment]
Bryce & Tim to tackle this, Bryce is currently working on improving the platform page already -- allowing platforms or instruments to be associated with individuals or organizations.

**Comment by timvdstap** [comment]
Just having a look at this: https://wiki.esipfed.org/MI_Platform -- seems to me like this field can be populated with a unique identification of the platform. Perhaps it just needs addition of a code type in the guidance text? E.g. 

This is a unique identification of the platform. Please provide the combination of code type and serial number, where available (e.g. IMO: 9781839).  If the platform is registered with [ICES](https://vocab.seadatanet.org/v_bodc_vocab_v2/search.asp?lib=C17), use the _conceptID_ identifier.

I don't know whether there is necessarily any guidance _against_ providing a URI or linking to the platform? For example in the case of a moored surface buoy, would it make sense to include: "StationID: 51WH0", or e.g. https://www.ndbc.noaa.gov/station_page.php?station=51wh0?

**Comment by BryceMarshall** [comment]
@timvdstap - I'm gathering that we need to accept both an identifier and a way to indicate which type of identifier it is. 
I'm assuming we can treat a URL/URI as self-describing in that respect.
Is it reasonable to enumerate the code types that a user might have? Thinking about a separate dropdown list to select that bit.

**Comment by fostermh** [comment]
Is there a defined list of platform ID providers? 

Are you suggesting a 'type' field should be added to the form @timvdstap?
