### ISSUE TITLE
DOI url bug between ckan and metadata form

### ISSUE THREAD

**Issue by pauline-chauvet** [cioos-siooc/metadata-entry-form#230]
When we put the DOI url in the form: https://doi.org/10.26071/ogsl-m3x6-fh43
 it says that the entry is not correct
![image](https://user-images.githubusercontent.com/70213496/219378809-f8766d2e-bf0e-4b40-81ff-ae3ebfa4d615.png)
However, if we only put the number:10.26071/ogsl-m3x6-fh43, then there is a problem in the catalog

without url
![image](https://user-images.githubusercontent.com/70213496/219379188-d00197fe-736f-47c6-aedf-b2811e615221.png)

with url
![image](https://user-images.githubusercontent.com/70213496/219379256-bdc62b35-c4e8-490b-80d5-60d3c6eff5b7.png)

**Comment by pauline-chauvet** [comment]
hope my issue is clear, otherwise, don't hesitate to contact me

**Comment by fostermh** [comment]
It appears that I need to adjust the parsing of DOI's in CKAN. I thought this was working but perhaps I'm not accounting for the dashes.  On a related note, it would be very convenient if the metadata form stored the full URL in the XML rather than just the identifier. Could we change the DOI input in the metadata form to allow/encourage full URLS?

**Comment by pauline-chauvet** [comment]
"Could we change the DOI input in the metadata form to allow/encourage full URLS?" 
 --
I agree with Mat as it would also be helpful when we use the eml for OBIS IPT, right now, I have to correct it manually

**Comment by n-a-t-e** [comment]
I agree as well, it should come out as a complete URL in the XML/YAML/EML/ERDDAP outputs

**Comment by n-a-t-e** [comment]
Reopening this - one last step needed is any records that have been saved without the https://doi.org/ prefix need to be update in the database. Otherwise these records appear as "invalid" in the metadata form, and eg can't use the download to XML/EML options

**Comment by fostermh** [comment]
I think the database update has been done, need to confirm.

**Comment by BryceMarshall** [comment]
It looks like all DOI URLs have been updated - though I did identify that there are ~120 entries that have that field populated with a non-DOI entry e.g.

```"datasetIdentifier": "https://doi.org/10.48689/736c4721-db8e-4116-a5f8-d9084126b135"```

vs

```"datasetIdentifier": "Eelgrass Extent Field Data (2018) - Kelp Beds"```

Is this something that needs to be addressed as well?

**Comment by fostermh** [comment]
I think that is ok for us but is perhaps something that @Br-Johnson, @timvdstap and @JessyBarrette  should know about for eh future

**Comment by JessyBarrette** [comment]
Thanks @fostermh @BryceMarshall Yes will address that in a coming sprint :)
