### ISSUE TITLE
Add a new licence for Environment and Climate Change Canada Data Servers

### ISSUE THREAD

**Issue by julieDionne** [cioos-siooc/metadata-entry-form#231]
We need to add a new license to the metadata form. Some new Environment Canada datasets will be linked to the datamart and this is the license they use.

EN : Environment and Climate Change Canada Data Servers End-use Licence
https://eccc-msc.github.io/open-data/licence/readme_en/

FR: Licence d’utilisation finale pour les serveurs de données d’Environnement et Changement climatique Canada
https://eccc-msc.github.io/open-data/licence/readme_fr/

**Comment by BryceMarshall** [comment]
Resolved by https://github.com/cioos-siooc/metadata-entry-form/pull/266
