### ISSUE TITLE
auto translation flag

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#233]
If the translation in the form is automatic, we will be flagging it as displaying a symbol in CKAN that indicates it might be a bad translation. So we need a way for the user to indicate that they have approved of the translation, to remove this flag.

We can use a checkbox or toggle says "I have verified this translation", or something like that

When the automatic translation button is clicked, the checkbox gets unchecked

This logic can be sorted out a bit more, should be clear to the user.

**Comment by fostermh** [comment]
related issue https://github.com/cioos-siooc/ckan/issues/187

**Comment by fostermh** [comment]
xml code snippet
```
<mdb:identificationInfo>
    <mri:MD_DataIdentification>
      <mri:citation>
        <cit:CI_Citation>
          <cit:title xsi:type="lan:PT_FreeText_PropertyType">
            <gco:CharacterString>Hakai Institute Juvenile Salmon Program Time Series</gco:CharacterString>
            <lan:PT_FreeText>
              <lan:textGroup xlink:href="https://cioos.ca/translation_method#amazon" xlink:role="translation" xlink:title="automatic">
                <lan:LocalisedCharacterString locale="#fr">Série chronologique du programme de saumon juvénile de l&#39;Institut Hakai</lan:LocalisedCharacterString>
              </lan:textGroup>
            </lan:PT_FreeText>
          </cit:title>
```

**Comment by fostermh** [comment]
the important part here being
```
<lan:textGroup xlink:href="https://cioos.ca/translation_method#amazon" xlink:role="translation" xlink:title="automatic">
```
