### ISSUE TITLE
Upgrade from outdated firebase-functions v3.xx - will cause breaking changes

### ISSUE THREAD

**Issue by sorochak** [cioos-siooc/metadata-entry-form#237]
When deploying firebase functions, a warning is received indicating the version of firebase-functions in use is outdated.
Warning also states upgrading will cause breaking changes.

List of breaking changes from the release notes found here: https://github.com/firebase/firebase-functions/releases?page=2

[v4.0.0](https://github.com/firebase/firebase-functions/releases/tag/v4.0.0)
Breaking Changes
Deprecated allowInvalidAppCheckToken option. Instead use
enforceAppCheck.
App Check enforcement on callable functions is disabled by default in v4.
Requests containing invalid App Check tokens won't be denied unless you
explicitly enable App Check enforcement using the new enforceAppCheck option.
Furthermore, when enforcement is enabled, callable functions will deny
all requests without App Check tokens.

Dropped support for Node.js versions 8, 10, and 12.
Dropped support for Admin SDK versions 8 and 9.
Removed the functions.handler namespace.
DataSnapshot passed to the Firebase Realtime Database trigger now
matches the DataSnapshot returned by the Admin SDK, with null values
removed.
Removed __trigger object on function handlers.
Reorganized source code location. This affects only apps that directly import files instead of using the recommend entry points specified in the
Reworked the apps library and removed lodash as a runtime dependency.
Change default behavior of function deploy to clear configurations not specified in the source code (e.g. change memory configuration in Google Cloud Console). Use preserveExternalChanges to keep existing behavior. See [docs](https://firebase.google.com/docs/functions/manage-functions#set_runtime_options) for more info.

**Comment by BryceMarshall** [comment]
@sorochak 
It looks like we've been on 4.x.x since last year - is this still a problem?

**Comment by BryceMarshall** [comment]
we could further upgrade to 4.7.x from 4.2.x - not sure how meaningful that would be

**Comment by sorochak** [comment]
maybe someone upgraded already? I no longer get the breaking changes warning.
