### ISSUE TITLE
Draft DOI sent to DataCite incorrectly and incompletely maps some fields

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/metadata-entry-form#243]
When I open up DataCite Fabrica to review draft DOIs for submitted metadata records I notice a few discrepancies. Missing fields I refer to are DataCite fields.

- [x] The URL element in DataCite is left empty but could be established with the dataset UUID appended to "https://catalogue.hakai.org/dataset/ca-cioos_" even before the record is published.
- [x] Creators: Only the affiliations of the authors of the metadata record are listed as creators in DataCite. Authors names are dropped entirely from Datacite. Affiliations should be nested under each creator
- [x] Datacite Resource type general could be auto-populated as 'dataset'

**Comment by sorochak** [comment]
@Br-Johnson for 'Creators', do we want all the contacts to be included as Creators, or only specific checked 'roles' ?
See screenshot:

![Screen Shot 2023-10-26 at 3 48 17 PM](https://github.com/cioos-siooc/metadata-entry-form/assets/18083401/919cee65-2471-42b4-97be-31309ea6d21c)

**Comment by Br-Johnson** [comment]
Everyone marked as ‘appear in citation’ except those marked publisher who
would go into the Publisher field in datacite

**Comment by sorochak** [comment]
Can you clarify exactly what you mean by 'affilitations should be nested under each creator' ?

**Comment by sorochak** [comment]
Can you clarify this request also: "The URL element in DataCite is left empty but could be established with the dataset UUID appended to "https://catalogue.hakai.org/dataset/ca-cioos_" even before the record is published"

**Comment by Br-Johnson** [comment]
> Can you clarify exactly what you mean by 'affilitations should be nested under each creator' ?

![image](https://github.com/cioos-siooc/metadata-entry-form/assets/26495640/f566bb0e-fbf3-49b2-ad6e-1109a4fe1f25)

Datacite JSON:
"creators": [
    {
      "name": "Johnson, Brett",
      "nameType": "Personal",
      "givenName": "Brett",
      "familyName": "Johnson",
      "affiliation": [
        {
          "name": "Hakai Institute",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/02pry0c91",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": [
        {
          "schemeUri": "https://orcid.org",
          "nameIdentifier": "https://orcid.org/0000-0001-9317-0364",
          "nameIdentifierScheme": "ORCID"
        }
      ]
    },

**Comment by Br-Johnson** [comment]
> Can you clarify this request also: "The URL element in DataCite is left empty but could be established with the dataset UUID appended to "https://catalogue.hakai.org/dataset/ca-cioos_" even before the record is published"



When records are drafted and sent to Datacite the URL field is left empty (in the example below I manually added it), but it could be populated by extracting the UUID from the ISO .xml (see <gco:CharacterString> in the pasted ISO xml snippet below and prepending "https://catalogue.hakai.org/dataset/ca-cioos_".

DataCite JSON:
```
{
  "id": "https://doi.org/10.21966/1.566666",
  "doi": "10.21966/1.566666",
  "url": "https://catalogue.hakai.org/dataset/ca-cioos_6c449900-c726-4e9a-b241-707711e253a7",
  "types": {
    "ris": "DATA",
    "bibtex": "misc",
    "citeproc": "dataset",
    "schemaOrg": "Dataset",
    "resourceType": "Dataset",
    "resourceTypeGeneral": "Dataset"
  },
```
ISO XML:
```
<mdb:metadataIdentifier>
    <mcc:MD_Identifier>
      <mcc:authority>
        <cit:CI_Citation>
          <cit:title>
            <gco:CharacterString>ca.cioos</gco:CharacterString>
          </cit:title>
        </cit:CI_Citation>
      </mcc:authority>
      <mcc:code>
        <gco:CharacterString>6c449900-c726-4e9a-b241-707711e253a7</gco:CharacterString>
      </mcc:code>
    </mcc:MD_Identifier>
  </mdb:metadataIdentifier>
  ```
