### ISSUE TITLE
Option to manually change resourceType in citation

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/metadata-entry-form#248]
related to https://github.com/cioos-siooc/metadata-entry-form/issues/240

Would it be possible to include a field to manually change the resourceType (currently defaults to [Data set]) in the recommended citation both in the Metadata Intake Form and CKAN? Data set is not an accurate representation of some research outputs currently in the Hakai Catalogue. See for a list: https://support.datacite.org/docs/what-are-the-resource-types-for-datacite-dois

**Comment by fostermh** [comment]
see https://github.com/cioos-siooc/metadata-entry-form/issues/240
are you thinking we should support the full list of resource types or only a subset?

**Comment by timvdstap** [comment]
I think a (small) subset would be sufficient. Realizing I'm potentially opening a can of worms here, but I think that the list might depend on the integration of the catalogue with an eventual Pubs server that Steve's working on, and what resources/outputs will be available there rather than through the catalogue. Currently the catalogue stores some protocols and a guidebook, but perhaps these might best become available through Pubs rather than on the catalogue?

However, for e.g. some Geospatial products I can imagine that they'll remain available through the Catalogue, see e.g.: https://catalogue.hakai.org/dataset/ca-cioos_5843a289-2c88-4253-bed8-25b5b58b1d79. I think this resource type would fall under <InteractiveResource> -- perhaps this is the only additional resource type that needs adding?

Happy for @Br-Johnson and @JessyBarrette to weigh in!

**Comment by Br-Johnson** [comment]
Based on our sprint planning meeting recently with Steve it would make sense to have those text based resources still available in the Hakai metadata catalogue and the would point to pdfs or whatever that are hosted on the pubs server. 

Personally I think the full list of resource types would be good unless there are explicit reasons not to allow certain types of resources.

**Comment by fostermh** [comment]
so how does the iso citation type https://wiki.esipfed.org/ISO_19115-3_Codelists#MD_ScopeCode
map to the apa citation reference type https://apastyle.apa.org/style-grammar-guidelines/references/examples
and then to the datacite resource type? https://support.datacite.org/docs/what-are-the-resource-types-for-datacite-dois

**Comment by Br-Johnson** [comment]
@timvdstap is putting together a table to do this. I imagine there must be some software that already maps datacite resource types to apa citations though?

**Comment by timvdstap** [comment]
From an initial investigation it seems to - as expected I think - open a larger can of worms. Perhaps we should first decide whether to include all resource types or perhaps focus on a subset? Seems like in mapping between citation styles there's sometimes additional annotation that need to be included (i.e. DataCite's 'Dissertation' can map to either 'Doctoral Dissertation' or 'Master's thesis') -- I'm not sure how to go about that?

**Comment by timvdstap** [comment]
Update: There is currently a PR for this request (#242), where resourceType is added as a field in the early stage of metadata entry. Depending on resourceType this "greys out" irrelevant fields, as well as update the resourceType in the recommended citation (i.e. for model data there'd be no platform tab). The field would have to go into Data Identification to assure proper mapping.
