### ISSUE TITLE
Improve EML.xml mapping

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/metadata-entry-form#253]
Main thing for Hakai over the first two days of the sprint are to consider what additional EML items Nate could add to the form. 

This is a CIOOS Biodata related task. [Julie’s powerpoint](https://docs.google.com/presentation/d/1ogL_5ymKKAwtjPtjuBR93yusj9LalF10nYhGDRf2ECc/edit#slide=id.p1) about mapping EML better. 

Biological data git branch has been made https://github.com/cioos-siooc/metadata-entry-form/tree/biological-data

**Comment by timvdstap** [comment]
I've created a `biological-branch` label so we can label any tickets/issues associated with the improvement of eml.xml mapping / the biological-data branch with that label.
