### ISSUE TITLE
eml.xml file download function broken

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/metadata-entry-form#261]
It seems it's no longer possible to download the eml.xml file from published records. The other formats seem to work still.

**Comment by timvdstap** [comment]
It seems that for many other records the entire download function no longer works either.

![image](https://github.com/cioos-siooc/metadata-entry-form/assets/62965116/faac549c-3268-4fe4-b011-6222ada0e69f)

**Comment by timvdstap** [comment]
Recently the requirement was added to include the http, without changing existing records. DOIs therefore still show up properly in CKAN but appear incomplete in the form. https://doi.org/ prefix will have to be added to make these records complete and allow download.

**Comment by sorochak** [comment]
@timvdstap Is this still broken? I'm able to download records, but maybe I'm looking in the wrong place. 
The https://doi.org/ prefix has been added to all the records last month.

**Comment by timvdstap** [comment]
Seems to work on my end! :-) I'll close this issue.
