### ISSUE TITLE
Polygon coordinates to bounding box coordinates

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/metadata-entry-form#263]
The IPT does not (currently) support polygon coordinates in the way that we are able to provide those coordinates through the Metadata Entry Form. Instead, in the eml there are fields for `westBoundingCoordinate`, `eastBoundingCoordinate`, `northBoundingCoordinate` and `southBoundingCoordinate`. I'm wondering what the best approach here could be, is there's any way to programmatically infer these bounding coordinates from polygon coordinates into the eml?

**Comment by n-a-t-e** [comment]
Yes, we can find the bounding box that fits the polygon
