### ISSUE TITLE
Select resource type (dataset, model, etc) on start page?

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-entry-form#264]
Depends on https://github.com/cioos-siooc/metadata-entry-form/issues/240
in our planning meeting, Steve suggested selecting the resource type i.e. 'Dataset','Model',etc on the start page rather than hiding it in the data identification tab.

This seems like a nice workflow to me. Thoughts?

**Comment by fostermh** [comment]
in the biological discussion today it was mentioned that we need to support Oceanographic VS Model VS Biological types. this would be a nice fit for this list and could hide/show and make fields required based on the inputs the user selects

**Comment by sorochak** [comment]
What are we wanting here? I remember we discussed a dropdown/radio buttons on the start page to select resource type.

What are all the resource types available, Oceanographic, Model, and Biological?

What do we want/need to happen when a resource type is selected?
