### ISSUE TITLE
Adding IPT-required fields to Metadata Form

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/metadata-entry-form#265]
Linked to https://github.com/cioos-siooc/metadata-entry-form/issues/253

Additional fields that need to be added to the form as they are required in the IPT:

eml:
-  dataset>coverage>geographicCoverage>**geographicDescription**
-  dataset>methods>**methodStep**
-  dataset>methods>sampling>**studyExtent**
-  dataset>methods>sampling>**samplingDescription**

Suggested guidance text in the form (as taken from the IPT):
**geograhicDescription** - A free text description of the geographic area in which the data was collected.
**methodStep** - This field allows for repeated sets of elements that document a series of methods and procedures used in the study, and the processing steps leading to the production of the data files. These include text descriptions of the procedures, relevant literature, software, instrumentation, source data and any quality control measures taken. Each method should be described in enough detail to allow other researchers to interpret and repeat, if required, the study.
**studyExtent** - This field represents both a specific sampling area and the sampling frequency (temporal boundaries, frequency of occurrence).
**samplingDescription** - This field allows for a text-based / human readable description of the sampling procedures used in the research project. The content of this element would be similar to a description of sampling procedures found in the methods section of a journal article.

**Comment by sjbruce** [comment]
When it comes to the **methodStep** section, it appears that there can be many items under each step which can include:
 - title
 - description
 - sampling (plus studyExtent, samplingDescription, spatialSamplingUnits and 1-n coverages/bounding boxes with descriptions)
 - qualityControl, 
 - dataSource (plus title, creator, distribution and contact)
 - instrumentation

Are all of these permutations to be supported or are we only shooting for a simplified version of this?

Can subsections like **studyExtent** appear outside of **methods** as well?

**Comment by timvdstap** [comment]
I think **studyExtent** can also appear under **project**, although this tree is optional. I'm not sure whether it makes sense to have all those permutations supported, personally I was imagining a relatively straight-forward and simplified free-text field to populate the <description> field.

**Comment by sjbruce** [comment]
Okay, well let's start with title & description and then we can work towards some of the more exotic options as needed.
