### ISSUE TITLE
Add URL test to ressources

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/metadata-entry-form#267]
It would be great to test within the form the Url provided by the user:

Return flag the url if a 404 code is return from that URL

I'm don't think this should however prevent a user from submitting a record since it can be expected sometimes that the URL will eventually be up and running (ex an erddap dataset).

**Comment by sorochak** [comment]
To do:

- [ ] implement debounce util function
- [ ] implement head request on the url - return status flag that says either url active or unreachable
