### ISSUE TITLE
Missing fields when drafting DataCite DOI

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/metadata-entry-form#270]
The majority of fields are mapped over to DataCite correctly, awesome work! @sorochak Upon reviewing the draft DOI in DataCite, wondering if the following things can be implemented:

- [x] Map version element 
- [x] If an organization is selected as 'Funder', this should be mapped into 'Funding References:funderName'.
- [x] Geolocations bounding box

Are there perhaps other roles that should be mapped to 'Contributors' (i.e. Distributor or Sponsor)? @Br-Johnson @JessyBarrette

**Comment by timvdstap** [comment]
@n-a-t-e Fields are not getting overwritten. When these fields are manually updated in DataCite, and then removed in the form before hitting 'update draft DOI', the fields remain populated in DataCite.

**Comment by JessyBarrette** [comment]
> Are there perhaps other roles that should be mapped to 'Contributors' (i.e. Distributor or Sponsor)?

Do we have the list of roles mapped to contributor? I'm wondering since there'a similar field that needs to be filled within the ACDD standard to ERDDAP output.

**Comment by timvdstap** [comment]
Update: 

Geolocation Bounding Boxes are now populated in DataCite even when polygon coordinates are provided.
Version element is not yet mapped over to DataCite, nor is the 'Funder' information.
