### ISSUE TITLE
Auto-update generated draft DOI when saving

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/metadata-entry-form#271]
Would it be possible for the generated draft DOI to be automatically updated when a draft record is saved in the metadata form?

And if the draft DOI is automatically updated, is there still a need for the 'Update draft DOI' button?

**Comment by sorochak** [comment]
it is possible - when the save button is clicked, to check the backend to see if the record has a DOI saved/attached to it already, and if so, update the DOI with Datacite.

**Comment by timvdstap** [comment]
We're removing the save button and auto-saving the form when changes are made.
