### ISSUE TITLE
Field: additional affiliation

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/metadata-entry-form#298]
In DataCite it's possible to add multiple affiliations to a contributor, wondering if it'd be possible to add this feature in the metadata intake form as well. 

![image](https://github.com/cioos-siooc/metadata-entry-form/assets/62965116/d884ecbc-3f36-4a04-9e13-1687c166955f)

Current workaround for people that have multiple affiliations is that we'd ask what the primary affiliation is, and then in the metadata tool duplicate the contact information, but making sure we 'uncheck' the `Appear in citation` box and including their secondary affiliation.

**Comment by fostermh** [comment]
The tricky bit is in the ISO standard, people are nested under Organization, not the other way around. So in order to make that work we would need to take the multiple Org's and reformat into the list that is manually created now. It's doable but a medium amount of work. Does this happen often?
