### ISSUE TITLE
Auto creation of GitHub Issue on submission of metadata record is broken

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/metadata-entry-form#307]
Hey @n-a-t-e or @sorochak. It looks like the automatic GitHub issue creation for when Hakai records are submitted feature is broken.

A couple of records have been submitted recently, but no new issue have been created in https://github.com/HakaiInstitute/metadata-review/

**Comment by sorochak** [comment]
`GITHUB_AUTH` env variable was missing from the Google Cloud Console. 

Will think about a way to test cloud function auth works on update?

**Comment by sorochak** [comment]
@Br-Johnson created a new issue to address catching this kind of error in the future:
https://github.com/cioos-siooc/metadata-entry-form/issues/309

**Comment by sorochak** [comment]
@Br-Johnson created a new issue to address catching this kind of error in the future:
https://github.com/cioos-siooc/metadata-entry-form/issues/309
