### ISSUE TITLE
Complete Documentation of Firebase Functions in README.md

### ISSUE THREAD

**Issue by sorochak** [cioos-siooc/metadata-entry-form#317]
While reviewing the Firebase functions directory (firebase-functions/), I noticed that the `README.md` file has been initiated with the beginning of a list of our Metadata tool cloud functions. This document is incomplete and does not fully cover all the Firebase functions currently deployed or their specifics.

I wonder if we should update/complete this list as documentation source for all the firebase functions. If so, should that exist in `firebase-functions/README` or should it be in the `Metadata-entry-form` project README.

**Comment by fostermh** [comment]
comment blocks  added inline with functions in code
