### ISSUE TITLE
Ressource Types? Which ones should we make available within the CIOOS metadata form

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/metadata-entry-form#345]
#322  is adding a ressourceType input within the form to give the ability to distribute more than just datasets within the form. We're planning on using the [DataCite ressource types available](https://support.datacite.org/docs/what-are-the-resource-types-for-datacite-dois). After more discussion, it was suggested to only present a subset of those for now and potentially add more as needed. The question is which ones should be included:

- [ ] Audiovisual
- [x] Book
- [ ] BookChapter
- [ ] Collection
- [ ] ComputationalNotebook
- [ ] ConferencePaper
- [ ] ConferenceProceeding
- [ ] DataPaper
- [x] Dataset
- [ ] Dissertation
- [ ] Event
- [ ] Image
- [ ] InteractiveResource
- [ ] Instrument
- [ ] Journal
- [ ] JournalArticle
- [x] Model
- [ ] OutputManagementPlan
- [ ] PeerReview
- [ ] PhysicalObject
- [ ] Preprint
- [x] Report
- [ ] Service
- [ ] Software
- [ ] Sound
- [ ] Standard
- [ ] StudyRegistration
- [x] Text
- [ ] Workflow
- [ ] Other

**Comment by Br-Johnson** [comment]
One conservative approach would be to list whats currently already in the catalogue: Datasets, Models, Reports, Book, Text (for the protocols in the catalogue)

**Comment by fostermh** [comment]
it's easy to start there and add more later

**Comment by JessyBarrette** [comment]
I would also add potentially: Software and preprints
