### ISSUE TITLE
CIOOS Metadata Form migration to CIOOS account.

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/metadata-entry-form#366]
The metadata-entry-form database is right now managed by the Hakai Institute and it is required to transfer the ownership of that database to the CIOOS organization via the CIOOS Google workspace.

In order to achieve this the following steps are required:

## Firebase
- [x] Generate new firebase accounts associated with the CIOOS organization
- [x] Create a `cioos-metadata-entry-form` project
    - [x] Create a `cioos-metadata-entry-form` database
    - [x] Create a `cioos-metadata-entry-form-dev` database
- [x] Create a `cioos-metadata-entry-form-dev` project
    - [x] Create a `cioos-metadata-entry-form-dev` database
- [ ] Transfer App related code to firebase
    - [x] Transfer functions
    - [x] Transfer rules

## Other systems configuration
I can see some environment variables in the project that would maybe need to be updated?
- [x] AWS translation?
- [x] Google Cloud API key?
- [x] ~Netlify?~
- [x] GMAIL? use a new email from cioos <form.notifications@cioos.ca>

## Update in the codebase 

- [x] `src\firebase.js` use https://console.firebase.google.com/project/cioos-metadata-form/settings/general/web:MjZhYmY5NDYtZGQyNi00MDk1LTkwZDctOTkyODgwZTFhNzBh
- [x] Add authorized pages in firebase: https://console.firebase.google.com/project/cioos-metadata-form/authentication/settings
- [ ] Update waf package running from a server:  `cioos-records-update\app.py`

## Setup google authentification
https://console.firebase.google.com/project/cioos-metadata-form-f8c47/authentication/providers

I would need a support cioos specific email address. Whoever set that up needs to be able to manage that group email ideally.
- [x] Add group it.support@cioos.ca

## Ideally while the system is down
- [ ] Transfer all CIOOS related data to the new dataset
    - [ ] `cioos-...form/cioos-...-form`
    - [ ] `cioos-...form/cioos-...-form-dev`: isn't use anymore since firebase functions are shared between databases 
    - [ ] `cioos-...form-dev/cioos-...-form-dev`
- Add firebase token to the GitHub secrets
    - [ ] FIREBASE_SERVICE_ACCOUNT_CIOOS_METADATA_FORM
    - [x] FIREBASE_TOKEN
    - [x] FIREBASE_TOKEN_DEV 
- [x] Test that metadata-entry-form GitHub form is now linked to the new database.

## Setup cioos-record-update on CIOOS server

Start a service on a cioos.ca server to retrieve the xml files
- [ ] Deploy service
- [ ] Add google service account 
- [ ] Add proxy access to the service

**Comment by fostermh** [comment]
list seems good. the amazon translate stuff requires an amazon account. I don't know if cioos has one or not. https://aws.amazon.com/translate/

didn't know there was any netlify involved, likely can be dropped.

the google API key should have been created during the firebace project creation process

the google email is just an address to use to send emails. I believe there is a notifications@cioos.ca or info@notifications@cioos.ca or something like that.

**Comment by JessyBarrette** [comment]
Do you have any idea what kind of emails is sent via this email address? I can certainly redirect to the CIOOS one? if it's not already setup that way. I can't really see what's setup right now since it's all set as secrets.

**Comment by fostermh** [comment]
An example of where the environment variables for gmail are used can be seen here https://github.com/cioos-siooc/metadata-entry-form/blob/main/firebase-functions/functions/notify.js#L14

It is used to email reviewers and authors of metadata records when the status changed. We used github issues to track this at hakai but other orgs do not have that set up.

**Comment by JessyBarrette** [comment]
So I did update some of the secrets in the repo:

- [x] `AWS_*` translation with aws
- [ ] `DATACITE_AUTH_HASH` I don't think I need to change that. I guess it's for hiding the datacite password in the UI
- [ ] `FIREBASE_SERVICE_ACCOUNT_CIOOS_METADATA_FORM` Not sure which one I should use the production or dev project
- [ ] `FIREBASE_TOKEN`: Not sure what it is now. 
- [ ] `FIREBASE_TOKEN_DEV`: Not sure what it is now and it doesn's seem to appear anywhere in the actions and the codebase.
- [x] `GMAIL_*`: all good
- [ ] `HAKAI_DOI_PREFIX`: I guess this predates the DataCite option in the admin
- [ ] `ISSUE_CREATOR_PAT`: I guess this is to create issues when a form is submitted. Not used by any CIOOS people but could be useful. 
- [x] ~`NETLIFY_*` DEPRECATED~
- [x] `REACT_APP_GOOGLE_CLOUD_API_KEY` coming form the Project setting page in firebase console
- [x] `REACT_APP_GOOGLE_CLOUD_API_KEY_DEV`coming form the Project setting page in firebase console

**Comment by JessyBarrette** [comment]
@fostermh can you help me figure out the FIREBASE_TOKEN where it comes from. 

I also found out that the `firebase_to_xml` as the firebase production dataset hardcoded in there.

**Comment by fostermh** [comment]
Hey @JessyBarrette have a look at the github action that uses it https://github.com/marketplace/actions/deploy-to-firebase-cloud-functions-only-functions you have to login to firebase from the command line to generate the token

**Comment by fostermh** [comment]
DATACITE_AUTH_HASH is for logging into a datacite account to generate DOI's from the form. Only Hakai was doing this. This setting was moved to the admin section of the database so that other orgs could do the same. environment variable is no longer needed.

**Comment by fostermh** [comment]
FIREBASE_SERVICE_ACCOUNT_CIOOS_METADATA_FORM is the service account json key. You can generate your own from the firebase console. example path: https://console.firebase.google.com/u/0/project/cioos-metadata-form/settings/serviceaccounts/adminsdk

**Comment by JessyBarrette** [comment]
> Hey @JessyBarrette have a look at the github action that uses it https://github.com/marketplace/actions/deploy-to-firebase-cloud-functions-only-functions you have to login to firebase from the command line to generate the token

Ok that seems to be account specific so no need to have a project specific token. Make sense that FIREBASE_TOKEN_DEV is never used in the repo actions.

> FIREBASE_SERVICE_ACCOUNT_CIOOS_METADATA_FORM is the service account json key. You can generate your own from the firebase console. example path: https://console.firebase.google.com/u/0/project/cioos-metadata-form/settings/serviceaccounts/adminsdk

Ok, so as I understand it, you copy in the secret the whole json file retrieved from firebase UI or google cloud ui.

**Comment by fostermh** [comment]
> Ok, so as I understand it, you copy in the secret the whole json file retrieved from firebase UI or google cloud ui.

Correct

**Comment by JessyBarrette** [comment]
Looks like also needed to transfert the list of users from one project to another. 

To do it, thanks to google Gemini! Via firebase cli:

1. Log to your account:
   ```bash
   firebase login
   ```
2. Connect to the original project
   ```bash
   firebase use cioos-metadata-form
   ```
3. Retrieve auth list
   ```bash
   firebase auth:export --format json user-production-original.json
   ```

4. Switch to the new project
   ```bash
   firebase use cioos-metadata-form-8d942 
   ```
   
5. Upload auth list to the new project
   ```bash
   firebase auth:export --format json user-production-newbkp.json
   ```

6. If old users connected to the new project while the transition was completed, you may have to delete their new account in the auth list of firebase.

**Comment by JessyBarrette** [comment]
I will summarize all this in a document and it would be great to have the whole repo rely only on a .env
