### ISSUE TITLE
Remove 'category' field

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#40]
We have a drop down for category in the form, and the options are from ISO. In `metadata-xml` we have this hard coded to 'oceans' since the options available mostly don't apply to us:

- farming
- biota
- boundaries
- climatologyMeteorologyAtmosphere
- economy
- elevation
- environment
- geoscientificInformation
- health
- imageryBaseMapsEarthCover
- intelligenceMilitary
- inlandWaters
- location
- oceans
- planningCadastre
- society
- structure
- transportation
- utilitiesCommunication
- extraTerrestrial
- disaster

I suggest we ditch this drop down entirely and stick with the hard coded value of 'oceans'

**Comment by raytula** [comment]
Hey @n-a-t-e just a note that additional categories may be relevant to Hakai and/or other organizations that Hakai may help use this form in the future.  I assume the list can be expanded then, but thought I would mention it.  Ray
