### ISSUE TITLE
allow editing of 'submitted' and 'published' records

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#55]
Right now the 'edit' button gets greyed out to the user once a record is submitted for review. Since there will be mistakes sometimes, we can remove that feature, and let people submit for review as much as they want. The reviewers will be notified each time the record is submitted for review. Could add some text to indicate to the user that the reviewers are being notified. Could do this for both records that have been submitted for review, and for records that have been published (by a reviewer)

**Comment by sjbruce** [comment]
Perhaps a Reject button for the reviewer that will change the status from submitted to blank or something else?

The reviewer's current options are publish and delete so this would allow them to kick it back to the submitter.  Perhaps a notes field so the issues can be contained with the record?  They just get ignored when it comes to publishing.

The user might also need to withdraw their submission if they realize they've submitted something prematurely.  A second email could be sent to reviewers that the submission has been withdrawn.  This would open up the edit and submit buttons again.

**Comment by n-a-t-e** [comment]
Simple version of this now exists in the form since 9b91e173e218c8cb2ab54b1a6912d21707a9b217. User can keep editing their submitted forms, and can withdraw their published forms for re-editing as draft
