### ISSUE TITLE
Incorrect platform role?

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-entry-form#71]
The Platform section shows a role, where the role codes appear to come from [CI_RoleCode](https://wiki.esipfed.org/ISO_19115-3_Codelists#CI_RoleCode). Maybe this role is meant to populate the mandatory [resourceScope](https://wiki.esipfed.org/ISO_19115-3_Codelists#MD_ScopeCode) instead? The only other option I can see would be the platform sponsor, but that is an optional field, whereas the form appears to require that a role be set.

**Comment by jeffcullis** [comment]
But on the other hand if this is meant to be the role for the sponsor, there should also be an option to provide the platform manufacturer name and contact info as well.

**Comment by n-a-t-e** [comment]
It's to populate this field, but it looks like this field is not required anymore in the current version of the profile. In that case I think we should get rid of this field

https://github.com/cioos-siooc/metadata-xml/blob/ef181ad320482788f88adf896be9b58f00e0eabc/metadata_xml/iso19115-cioos-template/main.j2#L635

**Comment by jeffcullis** [comment]
Seems like it could be useful to at least have the organization or individual name and an email for the group that is responsible for the platform manufacture/deployment. Not sure this is currently captured anywhere else in the platform section. Odum has an example of what this could look like here:
https://docs.google.com/spreadsheets/d/1j2Us0B3F4b3STj_lSE0B_VqS47PxmesifG2cugj0Mak/edit#gid=1090334653
