### ISSUE TITLE
CKAN harvest fails due to single-quote in keywords

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-entry-form#72]
Added some French keywords to the CMAR - Jordan Bay metadata record. When harvesting the output XML file into CKAN, I get the error:
`Validation Error: {u'Keywords': u'Tag "pression de l\'air" must be alphanumeric characters or symbols: -_.', `
Looking at the keywords entry in the XML file I see:
`<lan:LocalisedCharacterString locale="#fr"> pression de l&#39;air</lan:LocalisedCharacterString>`
Seems that the HTML code that is put into the XML is not rendering properly when imported by CKAN as plain text?

**Comment by fostermh** [comment]
Interestingly, Robert (hakai developer) is working on this exact issue with hakai metadata and our ckan instance. Perhaps an opportunity for collabiration.

**Comment by n-a-t-e** [comment]
I think I have fixed this but maybe haven't pushed the fix yet, will take a look in a sec

**Comment by n-a-t-e** [comment]
Looks like this issue isn't related to the metadata form as the XML is being generated properly, but good to know

**Comment by n-a-t-e** [comment]
Looks like this issue should be moved to the `metadata-xml` package as I think single quotes are allowed in XML content

**Comment by n-a-t-e** [comment]
should be fixed by https://github.com/cioos-siooc/metadata-xml/pull/73

**Comment by jeffcullis** [comment]
I wonder if the metadata-xml repo should eventually be merged into the metadata form repo? It could help track these kinds of issues across the two tools, and most users will mainly be interacting with the form it seems

**Comment by n-a-t-e** [comment]
I think that merging the repos makes sense to me, since going forward we will probably be adding new form fields that users request and then we don't have to track the addition of the new fields in two places. It wouldn't have to affect how the tool is used
