### ISSUE TITLE
Date 'now' breaks CKAN fetch harvest

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-entry-form#74]
Using the metadata form to create a record for an ongoing dataset causes the CKAN fetch harvester to fail. Message from logs:
```
sudo docker logs ckan_fetch_harvester
...
ckan.lib.search.common.SearchIndexError: Solr returned an error: (u"Solr responded with an error (HTTP 400): [Reason: Invalid Date String:'now']",)
```

**Comment by n-a-t-e** [comment]
Looks like it should be written as `<gml:endPosition indeterminatePosition="now"/>`

**Comment by jeffcullis** [comment]
Sounds good, thanks Nate.
