### ISSUE TITLE
Date timezone issue

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#76]
There's a bug with the date selectors where a different date gets selected than the one that the user picks.

The date selector uses a timestamp internally that is in UTC, and if the current date/time in UTC is 'tomorrow' (eg. 7pm Pacific, would be the next day UTC)

There is lot online about this issue -
https://github.com/mui-org/material-ui-pickers/issues/1526

It's also currently storing a time when the user has just selected a date

**Comment by rjbergerud** [comment]
@n-a-t-e  Does commit #55bb5f5 fix this?  Since noon UTC (default timezone for Date object) will always be the same day anywhere in Canada?

**Comment by n-a-t-e** [comment]
It seems to have fixed it yes, thanks.
