### ISSUE TITLE
multiple authors access to edit same record

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#78]
It would be useful if you could share the editing of a record with another user. On the UI side this could be a text/chip entry on a metadata record with a list of email addresses to share with. When a user logs in that has access to another user's records, they would see them on the 'Saved Records' list, maybe in a separate section. Maybe they could edit but not submit or delete.

**Comment by n-a-t-e** [comment]
could have a "Shared with me" section like in Google drive

**Comment by sorochak** [comment]
should the 'shared with me' section only be used to display unpublished records?
