### ISSUE TITLE
Map polygon longitudes >180 degrees 

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#81]
I can't find an equivalent for polygons to, eg, `bounds.getNorthEast().wrap()` which converts longitudes to +-180
Not sure if CKAN will care if our polygon has longitudes >180 degrees. To reproduce, zoom way out on the map and scroll to a different copy of the earth and create a polygon.

**Comment by rjbergerud** [comment]
You could do do `(x + 180) % 360 - 180`, but then open street maps will render polygons that pass through the 180d meridian incorrectly.
