### ISSUE TITLE
Add metadata publication date

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-entry-form#88]
We will need to track the date that the metadata record was published, so that CKAN knows when to update the record. Where will this go in the XML? We should probably sort out https://github.com/cioos-siooc/metadata-xml/issues/68 at the same time

**Comment by fostermh** [comment]
may also need to look at the metadata revision date.

My understanding is that everything under /mdb:dateInfo in the xml are metadata related dates

**Comment by n-a-t-e** [comment]
pretty sure this was resolved via `timeFirstPublished`.  (the time the form user first hit 'Publish record'). If the record is edited later this doesn't affect `timeFirstPublished`
