### ISSUE TITLE
Add additional licenses to Atlantic form

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-entry-form#89]
We'd like to add the NS open data license to the dropdown list:
https://novascotia.ca/opendata/licence.asp

While we're at it, we may also want to add the NL open data license:
https://opendata.gov.nl.ca/public/opendata/page/?page-id=licence

**Comment by fostermh** [comment]
@jeffcullis, if not already done, could you add an issue to the ckan repo for this as well? We will need to update/check the CKAN license file.
